[package]
name = "tabular"
version = "0.1.0"
authors = ["Jesse A. Tov <jesse.tov@gmail.com>"]

[features]
default = ["unicode-width"]

[dependencies]
unicode-width = { version = "0.1.5", optional = true }